apiVersion: v1
kind: Secret
metadata:
  name: minio-backup-secret
  namespace: logging
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  MINIO_ENDPOINT_URL: http://host.minikube.internal:9000
  S3_BUCKET: loki-backup
