#!/bin/bash
# ==============================================================================
# Resource adoption script for ldc tempo cutover.
#
# Purpose: the current tempo deployment on ldc was applied via plain
# manifests (kubectl apply), NOT via a real `helm install`. Resources have the
# chart's LABELS but are missing Helm's OWNERSHIP ANNOTATIONS
# (meta.helm.sh/release-name, meta.helm.sh/release-namespace), which Helm
# requires before it will manage an existing resource under a new release.
#
# This script patches ONLY annotations/labels - it does NOT delete, restart,
# or modify the spec of any resource. Safe to run against live resources.
#
# Run this BEFORE `helm upgrade --install`:
#   helm upgrade --install tempo . -n observability \
#     -f values.yaml -f values-ldc-prod.yaml
#
# NOTE: adopting the HTTPRoute "tempo" means you can SKIP the
# `kubectl delete httproute tempo -n observability` step that
# values-ldc-prod.yaml warns about - helm will adopt it instead.
# ==============================================================================

set -euo pipefail

NS="observability"
RELEASE="tempo"

adopt() {
  local resource="$1"
  echo "Adopting ${resource} -> release ${RELEASE}"
  kubectl annotate "${resource}" -n "${NS}" \
    "meta.helm.sh/release-name=${RELEASE}" \
    "meta.helm.sh/release-namespace=${NS}" \
    --overwrite || echo "  (skip: ${resource} not found)"
  kubectl label "${resource}" -n "${NS}" \
    "app.kubernetes.io/managed-by=Helm" \
    --overwrite || true
}

echo "=== Adopting resources for release: ${RELEASE} (ns: ${NS}) ==="

# Workloads
adopt "deploy/tempo-gateway"
adopt "deploy/tempo-distributor"
adopt "deploy/tempo-querier"
adopt "deploy/tempo-query-frontend"
adopt "deploy/tempo-compactor"
adopt "deploy/tempo-metrics-generator"
adopt "sts/tempo-ingester"
adopt "sts/tempo-memcached"

# Services (including headless/discovery ones rendered by the chart)
adopt "svc/tempo-gateway"
adopt "svc/tempo-distributor"
adopt "svc/tempo-distributor-discovery"
adopt "svc/tempo-ingester"
adopt "svc/tempo-ingester-discovery"
adopt "svc/tempo-querier"
adopt "svc/tempo-query-frontend"
adopt "svc/tempo-query-frontend-discovery"
adopt "svc/tempo-compactor"
adopt "svc/tempo-metrics-generator"
adopt "svc/tempo-metrics-generator-discovery"
adopt "svc/tempo-memcached"
adopt "svc/tempo-gossip-ring"

# ConfigMaps + ServiceAccount
adopt "cm/tempo-config"
adopt "cm/tempo-gateway"
adopt "cm/tempo-runtime"
adopt "sa/tempo"

# HTTPRoute (rendered via chart extraObjects - adopt to avoid delete/downtime)
adopt "httproute/tempo"

# HPA / PDB / ServiceMonitor - adopt IF they already exist live; the adopt()
# helper skips cleanly when they don't (e.g. ServiceMonitors are new).
adopt "hpa/tempo-gateway"
adopt "hpa/tempo-distributor"
adopt "hpa/tempo-querier"
adopt "hpa/tempo-query-frontend"
adopt "pdb/tempo-distributor"
adopt "pdb/tempo-ingester"
adopt "pdb/tempo-querier"
adopt "pdb/tempo-query-frontend"
adopt "servicemonitor/tempo-compactor"
adopt "servicemonitor/tempo-gateway"
adopt "servicemonitor/tempo-distributor"
adopt "servicemonitor/tempo-ingester"
adopt "servicemonitor/tempo-memcached"
adopt "servicemonitor/tempo-metrics-generator"
adopt "servicemonitor/tempo-querier"
adopt "servicemonitor/tempo-query-frontend"

# Deliberately NOT adopted:
#   - ReplicaSets/Pods/Endpoints  (auto-generated by controllers)
#   - svc/tempo-gateway-nodeport  (NOT rendered by the chart - manual add)

echo ""
echo "=== Adoption complete. Verify with: ==="
echo "kubectl get deploy tempo-gateway -n ${NS} -o jsonpath='{.metadata.annotations}'"
