{
 "title": "Redis Cluster Dashboard",
 "tags": [
  "ot-dashboard",
  "ot-redis-cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application_group",
    "label": "ApplicationGroup",
    "query": {
     "query": "label_values(redis_cluster_enabled,rems_application_group)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(redis_cluster_enabled,rems_service)"
    }
   },
   {
    "name": "pod",
    "label": "Instance",
    "query": {
     "query": "label_values(redis_cluster_enabled{rems_service=\"$service\"},pod)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(redis_instance_info{pod=\"$pod\"},role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Cluster Health",
     "type": "stat",
     "description": "Returns the cluster health status",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(redis_cluster_state{rems_application_group=\"$application_group\",rems_service=\"$service\"})",
       "legendFormat": "Redis Cluster health"
      }
     ]
    },
    {
     "title": "Cluster Uptime",
     "type": "gauge",
     "description": "Returns the total uptime (in seconds) of all Redis instances combined for the selected application group and service.",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(redis_uptime_in_seconds{rems_application_group=\"$application_group\",rems_service=\"$service\"})",
       "legendFormat": "Cluster Uptime"
      }
     ]
    },
    {
     "title": "Connected Clients",
     "type": "state-timeline",
     "description": "Returns the current number of connected clients per Redis instance for the selected application group and service.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(redis_connected_clients{rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\"})",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Redis Cluster Nodes",
     "type": "stat",
     "description": "Returns the number of Redis instances reporting cluster size metrics.",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 276 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(redis_cluster_size{rems_application_group=\"$application_group\", rems_service=\"$service\"})",
       "legendFormat": "Cluster Nodes"
      }
     ]
    },
    {
     "title": "Redis Cluster Size",
     "type": "stat",
     "description": "Returns the maximum cluster size (number of master nodes) observed across the selected Redis cluster.",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 276 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(redis_cluster_size{rems_application_group=\"$application_group\",rems_service=\"$service\"})",
       "legendFormat": "Number of Master Nodes in the cluster"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Replication Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected Slaves",
     "type": "state-timeline",
     "description": "Returns the number of replica (slave) nodes connected to each Redis master instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(redis_connected_slaves{rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\"})",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Redis Role",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (role) (redis_instance_info{rems_application_group=\"$application_group\", rems_service=~\"$service\", pod=\"$pod\"})",
       "legendFormat": "{{role}}"
      }
     ]
    },
    {
     "title": "Redis Replication Lag",
     "type": "stat",
     "description": "Returns the replication lag (in seconds) between Redis master and its connected replicas for the selected instance.",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(redis_connected_slave_lag_seconds{rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\", pod=\"$pod\"})",
       "legendFormat": "Replication Lag"
      }
     ]
    },
    {
     "title": "Cluster bus connections",
     "type": "stat",
     "description": "Returns the maximum number of cluster bus connections observed across Redis cluster nodes",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(redis_cluster_connections{rems_application_group=\"$application_group\",rems_service=\"$service\"})",
       "legendFormat": "Cluster Bus Connections"
      }
     ]
    },
    {
     "title": "Instance Uptime",
     "type": "gauge",
     "description": "Returns the uptime (in seconds) of the specific Redis instance",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_uptime_in_seconds{rems_application_group=\"$application_group\",rems_service=\"$service\",pod=\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Command Latency",
     "type": "timeseries",
     "description": "Returns the average execution time per Redis command (by command type)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(irate(redis_commands_duration_seconds_total{rems_application_group=\"$application_group\",rems_service=~\"$service\", pod=\"$pod\"}[$__rate_interval])) by (cmd) / avg(irate(redis_commands_total{rems_application_group=\"$application_group\",rems_service=~\"$service\", pod=\"$pod\"}[$__rate_interval])) by (cmd)",
       "legendFormat": "{{cmd}}"
      }
     ]
    },
    {
     "title": "Redis Commands Per Second",
     "type": "timeseries",
     "description": "Shows the number of commands processed by Redis per second, calculated using the rate of the total commands counter",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(redis_commands_processed_total{rems_application_group=~\"$application_group\",\r\n    rems_service=~\"$service\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Measures the memory usage by Redis in bytes.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(redis_memory_used_bytes{rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\",pod=\"$pod\"})",
       "legendFormat": "Used Memory"
      },
      {
       "expr": "sum(redis_memory_used_peak_bytes{rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\",pod=\"$pod\"})",
       "legendFormat": "Peak Memory"
      },
      {
       "expr": "sum(redis_memory_used_rss_bytes{rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\",pod=\"$pod\"})",
       "legendFormat": "RSS Memory"
      }
     ]
    },
    {
     "title": "CPU Usage Rate",
     "type": "timeseries",
     "description": "CPU usage by Redis, broken down by system and user time.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(redis_cpu_sys_seconds_total{rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Sys CPU"
      },
      {
       "expr": "sum(rate(redis_cpu_user_seconds_total{rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "User CPU"
      }
     ]
    },
    {
     "title": "Redis Keys: Expired & Evicted",
     "type": "timeseries",
     "description": "Shows Redis key lifecycle activity by displaying expired and evicted keys per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(redis_expired_keys_total{rems_application_group=~\"$application_group\", rems_service=~\"$service\", pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Expired/sec"
      },
      {
       "expr": "rate(redis_evicted_keys_total{rems_application_group=~\"$application_group\", rems_service=~\"$service\", pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Evicted/sec"
      }
     ]
    },
    {
     "title": "Hits / Misses & Hit Ratio",
     "type": "timeseries",
     "description": "Shows Redis cache performance by displaying hits/sec, misses/sec, and hit ratio (%) to evaluate cache efficiency.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(redis_keyspace_hits_total{rems_application_group=\"$application_group\", rems_service=\"$service\", pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Hits/sec"
      },
      {
       "expr": "rate(redis_keyspace_misses_total{rems_application_group=\"$application_group\", rems_service=\"$service\", pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Misses/sec"
      },
      {
       "expr": "rate(redis_keyspace_hits_total{rems_application_group=~\"$application_group\",\r\n    rems_service=~\"$service\"}[$__rate_interval]) / (rate(redis_keyspace_hits_total{rems_application_group=~\"$application_group\",\r\n    rems_service=~\"$service\"}[$__rate_interval]) + rate(redis_keyspace_misses_total{rems_application_group=~\"$application_group\",\r\n    rems_service=~\"$service\"}[$__rate_interval])) * 100",
       "legendFormat": "Hit Rate %"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O",
     "type": "timeseries",
     "description": "Rate of incoming and outgoing network traffic.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "B/s" } },
     "targets": [
      {
       "expr": "rate((redis_net_input_bytes_total{rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Input"
      },
      {
       "expr": "rate((redis_net_output_bytes_total{rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Output"
      }
     ]
    },
    {
     "title": "Client Output Buffer",
     "type": "timeseries",
     "description": "Displays memory consumed by client output.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "B/s" } },
     "targets": [
      {
       "expr": "(redis_client_recent_max_output_buffer_bytes{rems_application_group=\"$application_group\",rems_service=\"$service\",pod=\"$pod\"})[$__rate_interval]",
       "legendFormat": "Output"
      }
     ]
    },
    {
     "title": "Client Input Buffer",
     "type": "timeseries",
     "description": "Rate of incoming network traffic.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "B/s" } },
     "targets": [
      {
       "expr": "(redis_client_recent_max_input_buffer_bytes{rems_application_group=\"$application_group\",rems_service=\"$service\",pod=\"$pod\"})[$__rate_interval]",
       "legendFormat": "Input"
      }
     ]
    }
   ]
  }
 ]
}